config/routes.rb
Plaintextoffenders::Application.routes.draw do

  match 'about-us' => "pages#about_us", :as => 'about_us'
  match 'talk-to-us' => "pages#talk_to_us", :as => 'talk_to_us'
  match 'contact-us' => "pages#talk_to_us"
  match 'feed' => "offending_sites#feed", :format => 'atom', :as =>'feed'
  match 'rss' => "offending_sites#feed", :format => 'atom', :as =>'feed' # for backwards compatibility
  match 'search' => "offending_sites#search", :as =>'search'
  match 'terms' => "offending_sites#terms", :as =>'terms'
  match "check_site_url", :controller => "offending_sites", :action => "check_url"
  match 'create-new' => "offending_sites#new", :as => 'create_new'
  match 'site/:url' => "offending_sites#show_by_url", :constraints => { :url => /.*/ }, :as => 'show_by_url'

  resources :offending_sites, :only => [:index, :show, :new, :create, :feed, :search, :terms]

  namespace :admin do
    resources :offending_sites do
      member do
        get 'publish'
        get 'unpublish'
      end
    end
  end

  root :to => "offending_sites#index"

end

app/models/offending_site.rb
class OffendingSite < ActiveRecord::Base
  self.per_page = 10

  has_attached_file :screenshot

  validates :url, :presence => true, :uniqueness => true, :format => { :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix }
  validates :email, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}, :allow_blank => false
  validates :name, :presence => true
  validates_attachment_presence :screenshot
  validates :screenshot, :presence => true # needed for client_side_validations
  validates :terms_of_service, :acceptance => true # this does not have a column in the DB (no need to). It is here for validation reasons only.

  def short_url
    return nil if url.nil?
    url.gsub("http://","").gsub("www.", "")
  end

  def is_published=(val)
    write_attribute :is_published, val

    # set updated_at
    self.published_at = val ? Time.now : nil
  end

  def description=(val)
    # converting newlines
    val.gsub!(/\r\n?/, "\n")

    # escaping HTML to entities
    val = val.to_s.gsub('&', '&amp;').gsub('<', '&lt;').gsub('>', '&gt;')

    # Allow b, i and u
    %w(b i u).each { |x|
         val.gsub!(Regexp.new('&lt;(' + x + ')&gt;(.+?)&lt;/('+x+')&gt;',
                 Regexp::MULTILINE|Regexp::IGNORECASE),
                 "<\\1>\\2</\\1>")
        }

    # replacing newlines to <br> and <p> tags
    # wrapping text into paragraph
    val = val.gsub(/\n\n+/, "</p>\n\n<p>").
            gsub(/([^\n]\n)(?=[^\n])/, '\1<br />')

    write_attribute :description, val
  end

  # Static methods

  def OffendingSite.all_ordered
    OffendingSite.order("created_at DESC")
  end

  def OffendingSite.all_published_ordered
    OffendingSite.where(:is_published => true).order("published_at DESC")
  end

  def OffendingSite.search(search_string)
    OffendingSite.where("url like ?", "%#{search_string}%").where(:is_published => true).order("published_at DESC")
  end
end

app/controllers/admin/admin_controller.rb
require "digest/sha1"

class Admin::AdminController < ApplicationController
  layout "admin"
  before_filter :login

  protected
  def login
    authenticate_or_request_with_http_basic do |username, password|
      # encrypt password to match with configured one
      hash_pass = Digest::SHA1.hexdigest(password)

      username == APP_CONFIG['admin_username'] && hash_pass == APP_CONFIG['admin_password']
    end
  end
end

app/controllers/admin/offending_sites_controller.rb
class Admin::OffendingSitesController < Admin::AdminController
  def index
    @offending_sites = OffendingSite.all_ordered
  end

  def new
    @offending_site = OffendingSite.new
  end

  def create
    @offending_site = OffendingSite.new(params[:offending_site])

    if @offending_site.save
      redirect_to admin_offending_sites_url
    else
      render :action => "new"
    end
  end

   def edit
     @offending_site = get_offending_site
   end

  def update
    @offending_site = get_offending_site

    # Don't continue if @offending_site is null
    return if @offending_site.nil?

    # Update entity and then save to DB
    @offending_site.attributes = params[:offending_site]
    if @offending_site.save
      flash[:notice] = "Update finished successfully"
      redirect_to admin_offending_sites_url
    else
      render :action => "edit"
    end
  end

  def destroy
    offending_site = get_offending_site

    # Don't continue if @offending_site is null
    return if offending_site.nil?

    offending_site.destroy

    flash[:notice] = "Offending site was deleted successfully"
    redirect_to admin_offending_sites_url
  end

  def publish
    offending_site = get_offending_site

    # Don't continue if @offending_site is null
    return if offending_site.nil?

    offending_site.is_published = true
    offending_site.save!

    flash[:notice] = "The site #{offending_site.url} is now published"
    redirect_to admin_offending_sites_url
  end

  def unpublish
    offending_site = get_offending_site

    # Don't continue if @offending_site is null
    return if offending_site.nil?

    offending_site.is_published = false
    offending_site.save!

    flash[:notice] = "The site #{offending_site.url} is now UNpublished"
    redirect_to admin_offending_sites_url
  end

  private
  def get_offending_site
    offending_site = OffendingSite.where(:id => params[:id]).first

    # If ID is not found, return to list with a warning
    if offending_site.nil?
      flash[:error] = "Given ID could not be found"
      redirect_to admin_offending_sites_url
    end

    offending_site
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/offending_sites_controller.rb
class OffendingSitesController < ApplicationController
  def index
    @offending_sites = OffendingSite.all_published_ordered.paginate(:page => params[:page])

    respond_to do |format|
      format.html
      format.xml { render :xml => @offending_sites }
      format.json { render :json => @offending_sites }
    end
  end

  def feed
    @offending_sites = OffendingSite.all_published_ordered

    respond_to do |format|
      format.atom do
        render :layout => false
      end
    end

  end

  def search
     @offending_sites = OffendingSite.search(params[:q]).paginate(:page => params[:page])

    respond_to do |format|
      format.html { render "index"}
      format.xml { render :xml => @offending_sites }
      format.json { render :json => @offending_sites }
    end
  end

  def show
    @offending_site = OffendingSite.where(:id => params[:id]).first

    if @offending_site.nil? or not @offending_site.is_published
      redirect_to root_url and return
    end

    respond_to do |format|
      format.html
      format.xml { render :xml => @offending_site }
      format.json { render :json => @offending_site }
    end
  end

  def show_by_url
    url = params[:url]
    url = url.gsub('www.','')
    url = 'http://' + url unless url[0..6] == 'http://'

    @offending_site = OffendingSite.find_by_url(url)

    if @offending_site.nil? or not @offending_site.is_published
      redirect_to root_url and return
    end

    respond_to do |format|
      format.html { render "show" }
      format.xml { render :xml => @offending_site }
      format.json { render :json => @offending_site }
    end
  end

  def create
    @offending_site = OffendingSite.new(params[:offending_site])

    if @offending_site.save
      flash[:notice] = "Thank you! we will go through your submission soon and publish it to the site."
      redirect_to root_url
    else
      render :action => "new"
    end
  end

  def check_url
    url = params[:offending_site][:url]
    url = url.gsub('www.','')
    url = 'http://' + url unless url[0..6] == 'http://'
    @entity = OffendingSite.find_by_url(url)
    respond_to do |format|
      format.json { render :json => !@entity }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def talk_to_us
  end
end

app/helpers/admin/offending_sites_helper.rb
module Admin::OffendingSitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offending_sites_helper.rb
module OffendingSitesHelper
  def post_date_format(date)
    date.strftime("%B #{date.day.ordinalize}, %Y at %l:%M%p")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/offending_sites/_form.html.erb
<% if @offending_site.errors.any? %>
  <span style="color:red; font-weight: bold">Errors!</span>
  <ul>
    <% @offending_site.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:admin, @offending_site], :html => {:multipart => true } do |f| %>
    <div class="editor-label">
      <%= f.label :url %>
    </div>
    <div class="editor-input">
      <%= f.text_field :url %>
    </div>

    <div class="editor-label">
      <%= f.label :description %>
    </div>
    <div class="editor-input">
      <%= f.text_area :description %>
    </div>

    <div class="editor-label">
      <%= f.label :name, 'Creator name' %>
    </div>
    <div class="editor-input">
      <%= f.text_field :name %>
    </div>

    <div class="editor-label">
      <%= f.label :email, 'Creator email' %>
    </div>
    <div class="editor-input">
      <%= f.text_field :email %>
    </div>

    <div class="editor-label">
      <%= f.label :screenshot %>
    </div>
    <div class="editor-input">
      <%= f.file_field :screenshot %>
      <br/>
      <%= image_tag @offending_site.screenshot.url if @offending_site.screenshot? %>
    </div>

    <div class="editor-label">
      <%= f.label :is_published %>
    </div>
    <div class="editor-input">
      <%= f.check_box :is_published %>
    </div>

    <%= f.submit %>

<% end %>

app/views/admin/offending_sites/edit.html.erb
<h1>Edit an Offending Site - <%=@offending_site.url%></h1>

<%= render 'form' %>

app/views/admin/offending_sites/index.html.erb
<% unless flash[:notice].nil? %>
    <fieldset style="background-color: yellow">
      <legend>Notice!</legend>
      <%= flash[:notice] %>
    </fieldset>
<% end %>

<% unless flash[:error].nil? %>
    <fieldset style="background-color: yellow; border-color: red;">
      <legend style="color:red; font-weight: bold">ERROR!</legend>
      <%= flash[:error] %>
    </fieldset>
<% end %>


<%= link_to "Create new", new_admin_offending_site_url %>
<table>
  <thead>
    <tr>
      <td>ID</td>
      <td>Url</td>
      <td>Created by</td>
      <td>Added at</td>
      <td>Is published?</td>
      <td>Published at</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @offending_sites.each do |site| %>
       <tr>
         <td><%= site.id %></td>
         <td><a href="<%=site.url%>"><%=site.url%></a></td>
         <td><a href="mailto:<%=site.email%>"><%= site.name %></a></td>
         <td><%= site.created_at %></td>
         <td><%= site.is_published ? "V" : "" %></td>
         <td><%= site.published_at %></td>
         <td>
           <%= link_to "Edit", edit_admin_offending_site_path(site) %> |
           <%= link_to "View", [:admin, site] %> |
           <%= link_to "Delete", [:admin,site], :confirm => "Are you sure you want to delete this site?", :method=>"delete" %> |
           <% if site.is_published %>
            <%= link_to "Unpublish", { :action => "unpublish", :id => site.id }, :confirm => "This will hide the site from your visitors. Are you sure?" %>
           <% else %>
            <%= link_to "Publish", { :action => "publish", :id => site.id }, :confirm => "Once you confirm, the site will be publicly available. Are you sure?"  %> |
           <% end %>
         </td>
       </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/offending_sites/new.html.erb
<h1>Create an Offending Site</h1>

<%= render 'form' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plain Test Offenders: Admin Site</title>

  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1>Plain Text Offenders</h1>
<h2>Administration Console</h2>
<hr/>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plaintextoffenders</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, "jquery.validate.min" %>
  <%= auto_discovery_link_tag(:atom, feed_path) %>
  <%= favicon_link_tag 'favicon.png' %>
  <link rel="apple-touch-icon" href="<%= image_path "favicon.png" %>"/>


  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=775"/> <!-- iPhone -->
  <meta name="description" content="Did you just email me back my own password?!" />
</head>
<body>
<div id="content" class="clearfix">
    <div id="header" class="clearfix">
        <h1><%= link_to "Plain Text Offenders", root_url %></h1>
    </div>

    <div id="sidebar">
        <div id="description">Did you just email me back my own password?!</div>
        <%= link_to "About", about_us_url, :class => "page_link" %>
        <%= link_to "Talk to Us", talk_to_us_url, :class => "page_link" %>
        <%= link_to "Submit New", create_new_url, {:id => "submitNew", :class => "page_link"} %>
        <%= link_to "Feed", feed_url, :class => "page_link" %>
        <div id="search">
            <form action="<%=search_path%>" method="get">
                <label><span>Search</span></label>
                <input type="text" name="q" value="<%=params[:q]%>">
                <input id="search_submit" type="submit" value="Search" alt="Search">
            </form>
        </div>
    </div>

    <div id="offending_sites" class="clearfix">
        <%= yield %>

      <div id="footer">
          <div id="footer_content" class="clearfix">
            <%= yield :footer %>
          </div>
          <div id="footer_info">
            <p>Developed by <a href="http://IronShay.com">Shay Friedman</a></p>
            <p><strong>Brutal Simplicity</strong> theme by <a href="http://kevin.tumblr.com">Kevin Burg</a></p>
          </div>
        </div>
    </div>
</div>
</body>
</html>

<script type="text/javascript">
 var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-22530527-1']);
 _gaq.push(['_trackPageview']);
 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
 })();
</script>

app/views/offending_sites/_new.html.erb
<p>
  Send us an image of the proof that the website in question is storing your password in plain-text (for instance a screenshot of the email you got containing the password). An email with your password sent to you at any time except after registering is much more preferable (such as an email sent after clicking “forgot password” or getting it in password reminders), but an email containing your password as confirmation for registering is OK too.<br><br>
  Remember to always blank out the details you don’t want shown on the website. Please include the site’s domain and an explanation of what the website is in the description.<br><br>
  Submissions are held for moderation and queued.
</p>
<%= form_for @offending_site || OffendingSite.new, :html => {:id => 'new_site', :multipart => true } do |f| %>
    <table border="0" cellspacing="0" cellpadding="0" style="width:99%">
        <tr>
          <td class="required_label">Url</td>
          <td><%= f.text_field :url %></td>
        </tr>
      <tr>
        <td class="required_label">Screenshot</td>
        <td><%= f.file_field :screenshot %></td>
      </tr>
      <tr>
        <td class="required_label">Your name</td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td class="required_label">Your email</td>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
        <td colspan="2"><%= f.label :description %></td>
      </tr>
      <tr>
        <td colspan="2"><%= f.text_area :description %></td>
      </tr>
      <tr>
        <td colspan="2">
          <%= f.check_box :terms_of_service %>
          <%= f.label :terms_of_service, 'I accept the <a id="terms_link" target="_blank" href="/terms">terms of submission</a>'.html_safe %>
        </td>
      </tr>
    </table>

    <div style="width:99%; text-align:center;">
        <%= f.submit "Submit!" %>
    </div>

<% end %>

<div id="terms_of_submission_dialog" title="Terms of Submission" style="display:none;">
    <%= render :partial => "terms" %>
</div>

<script type="text/javascript">
    function openTerms() {
        $("#terms_of_submission_dialog").dialog(
                {
                    width: '500',
                    height: '470'
                }
        );
    }
    $(function() {
        $("#terms_link").click(function() {
            openTerms();
            return false;
        });

        $('#new_site').validate({
            rules:{
                "offending_site[url]" : {required: true, url: true, remote: '/check_site_url' },
                "offending_site[screenshot]": {required: true },
                "offending_site[name]" : {required: true },
                "offending_site[email]" : {required: true, email: true}
            },
            messages: {
                "offending_site[url]" : {
                    required: "Url is required",
                    url: "Url is invalid",
                    remote: "Url already exists on the server"
                },
                "offending_site[screenshot]" : "Screenshot is required",
                "offending_site[name]" : "Name is required",
                "offending_site[email]" : {
                    required: "Email is required",
                    email: "Email is invalid"
                }
            }
        });

        $('#new_site').submit(function() {
           if ($('#new_site').valid()) {
               if ($("#offending_site_terms_of_service:checked").val() != "1") {
                   alert('You must accept the terms of submission.');
                   return false;
               }
           }
        });
    });
</script>

app/views/offending_sites/_nothing_to_see.html.erb
<div class="post clearfix">
  <div class="date_and_notes">Oy Vey!</div>

  <div class="photo">
    <div class="caption">
      <p>
        Sorry, there is nothing to see here!
      </p>
      <p>
        &lt;hint&gt; Maybe consider changing your search string? &lt;/hint&gt;
      </p>
    </div>
    </div>
    <div class="just_notes clearfix"></div>
  </div>

app/views/offending_sites/_notice.html.erb
<div class="post clearfix">
  <div class="date_and_notes">Thank you!</div>

  <div class="photo">
    <div class="caption">
      <p>
        <%= flash[:notice] %>
      </p>
    </div>
    </div>
    <div class="just_notes clearfix"></div>
  </div>

app/views/offending_sites/_offending_site.html.erb
<div class="post clearfix">
  <div class="date_and_notes"><%= link_to_unless_current post_date_format(offending_site.published_at), show_by_url_url(offending_site.short_url) %></div>

  <div class="photo">
    <% if current_page?(show_by_url_url(offending_site.short_url)) %>
        <div class='spread'>
          <div class='twshare left'>
            <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="funonrails">Tweet</a>
            <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
          </div>
        </div>

        <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
        <fb:like href="" layout="button_count" show_faces="false" width="450" font=""></fb:like>
    <% end %>
    <div class="photo_holder">
      <%= image_tag offending_site.screenshot.url %>
    </div>
    <div class="caption">
      <%= offending_site.url %>
      <p>
        <%= raw offending_site.description %>
      </p>
    </div>
    </div>
    <div class="just_notes clearfix"></div>
  </div>

app/views/offending_sites/_terms.html.erb
<ol>
        <li>
            <h3>You have permission to post this.</h3>
            <p>
                You represent and warrant that you own all rights to any content submitted. You will indemnify and hold harmless this site, its parents, subsidiaries, affiliates, customers, vendors, hosts, officers and employees from any liability, damage or cost (including reasonable attorneys. fees and cost) from (i) any claim or demand made by any third party due to or arising out of any content you submit.            </p>
            <br/>
        </li>
        <li>
            <h3>This site may distribute this post.</h3>
            <p>
                By uploading, submitting or otherwise disclosing or distributing content for display or inclusion on this site, you give this site unlimited license in perpetuity to the content and the information therein.            </p>
        </li>
</ol>

app/views/offending_sites/index.html.erb
<% unless flash[:notice].nil? %>
    <%= render :partial => "notice" %>
<% end %>

<% if @offending_sites.nil? or @offending_sites.size == 0 %>
    <%= render :partial => "nothing_to_see" %>
<% end %>

<%= render :partial => @offending_sites %>

<% unless @offending_sites.nil? or @offending_sites.size == 0 %>
    <% content_for :footer do %>
        <% current_page_number = (params[:page] || "1").to_i %>

        <% if current_page_number > 1 %>
            <a id="newer_posts" href="<%="#{offending_sites_url}?page=#{current_page_number-1}" %>">&#171; Newer posts</a> &nbsp;&nbsp;
        <% end %>

        <div class="page_of clearfix">
          <strong>Page <%=current_page_number%></strong>
          <span>of <%=@offending_sites.total_pages%></span>
        </div>

        <% if current_page_number < @offending_sites.total_pages %>
            <a id="older_posts" href="<%="#{offending_sites_url}?page=#{current_page_number+1}" %>">Older posts &#187;</a>
        <% end %>

    <% end %>
<% end %>

app/views/offending_sites/new.html.erb
<div class="post clearfix">
  <div class="date_and_notes">Submit New</div>

  <div class="photo">
    <div class="caption">
      <% if not @offending_site.nil? and @offending_site.errors.any? %>
          <span style="color:red; font-weight: bold">Errors!</span>
          <ul>
            <% @offending_site.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>

        <%= render :partial => "new" %>
    </div>
    </div>
    <div class="just_notes clearfix"></div>
  </div>

app/views/offending_sites/show.html.erb
<%= render :partial => @offending_site %>

<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'plaintextoffenders';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/offending_sites/terms.html.erb
<div class="post clearfix">
  <div class="date_and_notes">Terms of Submission</div>

  <div class="photo">
    <div class="caption">
        <%= render :partial => "terms" %>
    </div>
    </div>
    <div class="just_notes clearfix"></div>
  </div>

app/views/pages/about_us.html.erb
<div class="post clearfix">
  <div class="date_and_notes">About Us</div>

  <div class="photo">
    <div class="caption">
      <div class="regular_body">
        <p></p>

        <p>A website storing a password in plain text means that <strong>your password </strong>is there, waiting for
          someone to come and take it. It doesn’t even matter if you’ve created the strongest possible password. It’s
          just there.</p>

        <p>Whether it’s someone
          <a title="Gawker Media Websites Hacked, Staff and User Passwords Leaked" href="http://www.wired.com/threatlevel/2010/12/gawker-hacked/">hacking
            into their servers</a>,
          <a title="Serious SQL flaw could have compromised millions of Rockyou.com users" href="http://www.net-security.org/secworld.php?id=8612">using
            a simple flaw in their site</a> or even
          <a title="Never store passwords in a database!" href="http://blog.moertel.com/articles/2006/12/15/never-store-passwords-in-a-database">stealing
            their backups</a>,
          <a title="RockYou Hacker: 30% of Sites Store Plain Text Passwords" href="http://www.readwriteweb.com/archives/rockyou_hacker_30_of_sites_store_plain_text_passwords.php">over
            30% of sites store plain text passwords</a>.</p>

        <p>We’re tired of websites abusing our trust and storing our passwords in plain text, exposing us to danger.
          <strong>Here we put websites we believe to be practicing this to shame.</strong></p>

        <p>Found a text offender? Anonymously
          <a title="Submit" href="http://plaintextoffenders.com/submit">submit it to us</a> and put it to shame!</p>

        <p>Are you a developer? Read about
          <a title="How To Safely Store A Password" href="http://codahale.com/how-to-safely-store-a-password/">what you
            can do to solve it on your website</a>.</p>

        <p>More reading on why even
          <a href="http://plaintextoffenders.com/post/7006690494/whats-so-wrong-about-sending-a-new-password-in">just
            sending the password</a> via email without storing it in plain text is bad.</p>

        <p>Created by <a title="@hmemcpy on twitter" href="https://twitter.com/hmemcpy">@hmemcpy</a> and
          <a title="@omervk on twitter" href="https://twitter.com/omervk">@omervk</a>.</p>

        <p>Developed by <a title="@ironshay on twitter" href="http://twitter.com/ironshay">@ironshay</a>.</p>

        <p><a href="http://www.flickr.com/photos/michaelriedel_at/3604097386/">Photo</a> by Michael Reidel cc-by</p>

        <p></p>
      </div>
    </div>
  </div>
  <div class="just_notes clearfix"></div>
</div>

app/views/pages/talk_to_us.html.erb
<div class="post clearfix">
  <div class="date_and_notes">Talk to Us</div>

  <div class="photo">
    <div class="caption">
        <script type="text/javascript"> id = 111870; </script>
        <script type="text/javascript" src="http://kontactr.com/wp.js"></script>
    </div>
    </div>
    <div class="just_notes clearfix"></div>
  </div>